const std = @import("std");

const mcp = @import("mcp");
const mcio = mcp.packetio;
const mcv = mcp.vlatest;

// damage type js gen
//for(let i = 0; i < data.length; i += 1) {
//    let item = data[i];
//    console.log(".{");
//    console.log(".name = \"" + item.name + "\",");
//    console.log(".id = " + item.id + ",");
//    console.log(".element = .{");
//    console.log(".message_id = \"" + item.element.message_id + "\",");
//    console.log(".scaling = ." + item.element.scaling + ",");
//    console.log(".exhaustion = " + item.element.exhaustion + ",");
//    if(typeof item.effects !== "undefined") {
//        console.log(".effects = ." + item.element.effects + ",");
//    }
//    if(typeof item.death_message_type !== "undefined") {
//        console.log(".death_message_type = ." + item.element.death_message_type + ",");
//    }
//    console.log("},");
//    console.log("},");
//}

pub const default_damage_types = .{
    .{
        .name = "minecraft:arrow",
        .id = 0,
        .element = .{
            .message_id = "arrow",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0.1,
        },
    },
    .{
        .name = "minecraft:bad_respawn_point",
        .id = 1,
        .element = .{
            .message_id = "badRespawnPoint",
            .scaling = .always,
            .exhaustion = 0.1,
        },
    },
    .{
        .name = "minecraft:cactus",
        .id = 2,
        .element = .{
            .message_id = "cactus",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0.1,
        },
    },
    .{
        .name = "minecraft:cramming",
        .id = 3,
        .element = .{
            .message_id = "cramming",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0,
        },
    },
    .{
        .name = "minecraft:dragon_breath",
        .id = 4,
        .element = .{
            .message_id = "dragonBreath",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0,
        },
    },
    .{
        .name = "minecraft:drown",
        .id = 5,
        .element = .{
            .message_id = "drown",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0,
        },
    },
    .{
        .name = "minecraft:dry_out",
        .id = 6,
        .element = .{
            .message_id = "dryout",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0.1,
        },
    },
    .{
        .name = "minecraft:explosion",
        .id = 7,
        .element = .{
            .message_id = "explosion",
            .scaling = .always,
            .exhaustion = 0.1,
        },
    },
    .{
        .name = "minecraft:fall",
        .id = 8,
        .element = .{
            .message_id = "fall",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0,
        },
    },
    .{
        .name = "minecraft:falling_anvil",
        .id = 9,
        .element = .{
            .message_id = "anvil",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0.1,
        },
    },
    .{
        .name = "minecraft:falling_block",
        .id = 10,
        .element = .{
            .message_id = "fallingBlock",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0.1,
        },
    },
    .{
        .name = "minecraft:falling_stalactite",
        .id = 11,
        .element = .{
            .message_id = "fallingStalactite",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0.1,
        },
    },
    .{
        .name = "minecraft:fireball",
        .id = 12,
        .element = .{
            .message_id = "fireball",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0.1,
        },
    },
    .{
        .name = "minecraft:fireworks",
        .id = 13,
        .element = .{
            .message_id = "fireworks",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0.1,
        },
    },
    .{
        .name = "minecraft:fly_into_wall",
        .id = 14,
        .element = .{
            .message_id = "flyIntoWall",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0,
        },
    },
    .{
        .name = "minecraft:freeze",
        .id = 15,
        .element = .{
            .message_id = "freeze",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0,
        },
    },
    .{
        .name = "minecraft:generic",
        .id = 16,
        .element = .{
            .message_id = "generic",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0,
        },
    },
    .{
        .name = "minecraft:generic_kill",
        .id = 17,
        .element = .{
            .message_id = "genericKill",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0,
        },
    },
    .{
        .name = "minecraft:hot_floor",
        .id = 18,
        .element = .{
            .message_id = "hotFloor",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0.1,
        },
    },
    .{
        .name = "minecraft:in_fire",
        .id = 19,
        .element = .{
            .message_id = "inFire",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0.1,
        },
    },
    .{
        .name = "minecraft:in_wall",
        .id = 20,
        .element = .{
            .message_id = "inWall",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0,
        },
    },
    .{
        .name = "minecraft:indirect_magic",
        .id = 21,
        .element = .{
            .message_id = "indirectMagic",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0,
        },
    },
    .{
        .name = "minecraft:lava",
        .id = 22,
        .element = .{
            .message_id = "lava",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0.1,
        },
    },
    .{
        .name = "minecraft:lightning_bolt",
        .id = 23,
        .element = .{
            .message_id = "lightningBolt",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0.1,
        },
    },
    .{
        .name = "minecraft:magic",
        .id = 24,
        .element = .{
            .message_id = "magic",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0,
        },
    },
    .{
        .name = "minecraft:mob_attack",
        .id = 25,
        .element = .{
            .message_id = "mob",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0.1,
        },
    },
    .{
        .name = "minecraft:mob_attack_no_aggro",
        .id = 26,
        .element = .{
            .message_id = "mob",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0.1,
        },
    },
    .{
        .name = "minecraft:mob_projectile",
        .id = 27,
        .element = .{
            .message_id = "mob",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0.1,
        },
    },
    .{
        .name = "minecraft:on_fire",
        .id = 28,
        .element = .{
            .message_id = "onFire",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0,
        },
    },
    .{
        .name = "minecraft:out_of_world",
        .id = 29,
        .element = .{
            .message_id = "outOfWorld",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0,
        },
    },
    .{
        .name = "minecraft:outside_border",
        .id = 30,
        .element = .{
            .message_id = "outsideBorder",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0,
        },
    },
    .{
        .name = "minecraft:player_attack",
        .id = 31,
        .element = .{
            .message_id = "player",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0.1,
        },
    },
    .{
        .name = "minecraft:player_explosion",
        .id = 32,
        .element = .{
            .message_id = "explosion.player",
            .scaling = .always,
            .exhaustion = 0.1,
        },
    },
    .{
        .name = "minecraft:sonic_boom",
        .id = 33,
        .element = .{
            .message_id = "sonic_boom",
            .scaling = .always,
            .exhaustion = 0,
        },
    },
    .{
        .name = "minecraft:stalagmite",
        .id = 34,
        .element = .{
            .message_id = "stalagmite",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0,
        },
    },
    .{
        .name = "minecraft:starve",
        .id = 35,
        .element = .{
            .message_id = "starve",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0,
        },
    },
    .{
        .name = "minecraft:sting",
        .id = 36,
        .element = .{
            .message_id = "sting",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0.1,
        },
    },
    .{
        .name = "minecraft:sweet_berry_bush",
        .id = 37,
        .element = .{
            .message_id = "sweetBerryBush",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0.1,
        },
    },
    .{
        .name = "minecraft:thorns",
        .id = 38,
        .element = .{
            .message_id = "thorns",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0.1,
        },
    },
    .{
        .name = "minecraft:thrown",
        .id = 39,
        .element = .{
            .message_id = "thrown",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0.1,
        },
    },
    .{
        .name = "minecraft:trident",
        .id = 40,
        .element = .{
            .message_id = "trident",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0.1,
        },
    },
    .{
        .name = "minecraft:unattributed_fireball",
        .id = 41,
        .element = .{
            .message_id = "onFire",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0.1,
        },
    },
    .{
        .name = "minecraft:wither",
        .id = 42,
        .element = .{
            .message_id = "wither",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0,
        },
    },
    .{
        .name = "minecraft:wither_skull",
        .id = 43,
        .element = .{
            .message_id = "witherSkull",
            .scaling = .when_caused_by_living_non_player,
            .exhaustion = 0.1,
        },
    },
};

pub const default_biomes = .{
    // taken from vanilla registry
    .{
        .name = "minecraft:badlands",
        .id = 0,
        .element = .{
            .has_precipitation = false,
            .temperature = 2,
            .temperature_modifier = null,
            .downfall = 0,
            .effects = .{
                .fog_color = 12638463,
                .water_color = 4159204,
                .water_fog_color = 329011,
                .sky_color = 7254527,
                .foliage_color = 10387789,
                .grass_color = 9470285,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = .{
                    .sound = "minecraft:music.overworld.badlands",
                    .min_delay = 12000,
                    .max_delay = 24000,
                    .replace_current_music = false,
                },
            },
        },
    },
    .{
        .name = "minecraft:bamboo_jungle",
        .id = 1,
        .element = .{
            .has_precipitation = true,
            .temperature = 0.949999988079071,
            .temperature_modifier = null,
            .downfall = 0.8999999761581421,
            .effects = .{
                .fog_color = 12638463,
                .water_color = 4159204,
                .water_fog_color = 329011,
                .sky_color = 7842047,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = .{
                    .sound = "minecraft:music.overworld.bamboo_jungle",
                    .min_delay = 12000,
                    .max_delay = 24000,
                    .replace_current_music = false,
                },
            },
        },
    },
    .{
        .name = "minecraft:basalt_deltas",
        .id = 2,
        .element = .{
            .has_precipitation = false,
            .temperature = 2,
            .temperature_modifier = null,
            .downfall = 0,
            .effects = .{
                .fog_color = 6840176,
                .water_color = 4159204,
                .water_fog_color = 329011,
                .sky_color = 7254527,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = null,
                .particle = .{
                    .options = .{
                        .type = "minecraft:white_ash",
                        .value = null,
                    },
                    .probability = 0.1180933341383934,
                },
                .ambient_sound = .{ .string = "minecraft:ambient.basalt_deltas.loop" },
                .mood_sound = .{
                    .sound = "minecraft:ambient.basalt_deltas.mood",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = .{
                    .sound = "minecraft:ambient.basalt_deltas.additions",
                    .tick_chance = 0.0111,
                },
                .music = .{
                    .sound = "minecraft:music.nether.basalt_deltas",
                    .min_delay = 12000,
                    .max_delay = 24000,
                    .replace_current_music = false,
                },
            },
        },
    },
    .{
        .name = "minecraft:beach",
        .id = 3,
        .element = .{
            .has_precipitation = true,
            .temperature = 0.800000011920929,
            .temperature_modifier = null,
            .downfall = 0.4000000059604645,
            .effects = .{
                .fog_color = 12638463,
                .water_color = 4159204,
                .water_fog_color = 329011,
                .sky_color = 7907327,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = null,
            },
        },
    },
    .{
        .name = "minecraft:birch_forest",
        .id = 4,
        .element = .{
            .has_precipitation = true,
            .temperature = 0.6000000238418579,
            .temperature_modifier = null,
            .downfall = 0.6000000238418579,
            .effects = .{
                .fog_color = 12638463,
                .water_color = 4159204,
                .water_fog_color = 329011,
                .sky_color = 8037887,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = .{
                    .sound = "minecraft:music.overworld.forest",
                    .min_delay = 12000,
                    .max_delay = 24000,
                    .replace_current_music = false,
                },
            },
        },
    },
    .{
        .name = "minecraft:cherry_grove",
        .id = 5,
        .element = .{
            .has_precipitation = true,
            .temperature = 0.5,
            .temperature_modifier = null,
            .downfall = 0.800000011920929,
            .effects = .{
                .fog_color = 12638463,
                .water_color = 6141935,
                .water_fog_color = 6141935,
                .sky_color = 8103167,
                .foliage_color = 11983713,
                .grass_color = 11983713,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = .{
                    .sound = "minecraft:music.overworld.cherry_grove",
                    .min_delay = 12000,
                    .max_delay = 24000,
                    .replace_current_music = false,
                },
            },
        },
    },
    .{
        .name = "minecraft:cold_ocean",
        .id = 6,
        .element = .{
            .has_precipitation = true,
            .temperature = 0.5,
            .temperature_modifier = null,
            .downfall = 0.5,
            .effects = .{
                .fog_color = 12638463,
                .water_color = 4020182,
                .water_fog_color = 329011,
                .sky_color = 8103167,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = null,
            },
        },
    },
    .{
        .name = "minecraft:crimson_forest",
        .id = 7,
        .element = .{
            .has_precipitation = false,
            .temperature = 2,
            .temperature_modifier = null,
            .downfall = 0,
            .effects = .{
                .fog_color = 3343107,
                .water_color = 4159204,
                .water_fog_color = 329011,
                .sky_color = 7254527,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = null,
                .particle = .{
                    .options = .{
                        .type = "minecraft:crimson_spore",
                        .value = null,
                    },
                    .probability = 0.02500000037252903,
                },
                .ambient_sound = .{ .string = "minecraft:ambient.crimson_forest.loop" },
                .mood_sound = .{
                    .sound = "minecraft:ambient.crimson_forest.mood",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = .{
                    .sound = "minecraft:ambient.crimson_forest.additions",
                    .tick_chance = 0.0111,
                },
                .music = .{
                    .sound = "minecraft:music.nether.crimson_forest",
                    .min_delay = 12000,
                    .max_delay = 24000,
                    .replace_current_music = false,
                },
            },
        },
    },
    .{
        .name = "minecraft:dark_forest",
        .id = 8,
        .element = .{
            .has_precipitation = true,
            .temperature = 0.699999988079071,
            .temperature_modifier = null,
            .downfall = 0.800000011920929,
            .effects = .{
                .fog_color = 12638463,
                .water_color = 4159204,
                .water_fog_color = 329011,
                .sky_color = 7972607,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = "dark_forest",
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = .{
                    .sound = "minecraft:music.overworld.forest",
                    .min_delay = 12000,
                    .max_delay = 24000,
                    .replace_current_music = false,
                },
            },
        },
    },
    .{
        .name = "minecraft:deep_cold_ocean",
        .id = 9,
        .element = .{
            .has_precipitation = true,
            .temperature = 0.5,
            .temperature_modifier = null,
            .downfall = 0.5,
            .effects = .{
                .fog_color = 12638463,
                .water_color = 4020182,
                .water_fog_color = 329011,
                .sky_color = 8103167,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = null,
            },
        },
    },
    .{
        .name = "minecraft:deep_dark",
        .id = 10,
        .element = .{
            .has_precipitation = true,
            .temperature = 0.800000011920929,
            .temperature_modifier = null,
            .downfall = 0.4000000059604645,
            .effects = .{
                .fog_color = 12638463,
                .water_color = 4159204,
                .water_fog_color = 329011,
                .sky_color = 7907327,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = .{
                    .sound = "minecraft:music.overworld.deep_dark",
                    .min_delay = 12000,
                    .max_delay = 24000,
                    .replace_current_music = false,
                },
            },
        },
    },
    .{
        .name = "minecraft:deep_frozen_ocean",
        .id = 11,
        .element = .{
            .has_precipitation = true,
            .temperature = 0.5,
            .temperature_modifier = "frozen",
            .downfall = 0.5,
            .effects = .{
                .fog_color = 12638463,
                .water_color = 3750089,
                .water_fog_color = 329011,
                .sky_color = 8103167,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = null,
            },
        },
    },
    .{
        .name = "minecraft:deep_lukewarm_ocean",
        .id = 12,
        .element = .{
            .has_precipitation = true,
            .temperature = 0.5,
            .temperature_modifier = null,
            .downfall = 0.5,
            .effects = .{
                .fog_color = 12638463,
                .water_color = 4566514,
                .water_fog_color = 267827,
                .sky_color = 8103167,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = null,
            },
        },
    },
    .{
        .name = "minecraft:deep_ocean",
        .id = 13,
        .element = .{
            .has_precipitation = true,
            .temperature = 0.5,
            .temperature_modifier = null,
            .downfall = 0.5,
            .effects = .{
                .fog_color = 12638463,
                .water_color = 4159204,
                .water_fog_color = 329011,
                .sky_color = 8103167,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = null,
            },
        },
    },
    .{
        .name = "minecraft:desert",
        .id = 14,
        .element = .{
            .has_precipitation = false,
            .temperature = 2,
            .temperature_modifier = null,
            .downfall = 0,
            .effects = .{
                .fog_color = 12638463,
                .water_color = 4159204,
                .water_fog_color = 329011,
                .sky_color = 7254527,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = .{
                    .sound = "minecraft:music.overworld.desert",
                    .min_delay = 12000,
                    .max_delay = 24000,
                    .replace_current_music = false,
                },
            },
        },
    },
    .{
        .name = "minecraft:dripstone_caves",
        .id = 15,
        .element = .{
            .has_precipitation = true,
            .temperature = 0.800000011920929,
            .temperature_modifier = null,
            .downfall = 0.4000000059604645,
            .effects = .{
                .fog_color = 12638463,
                .water_color = 4159204,
                .water_fog_color = 329011,
                .sky_color = 7907327,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = .{
                    .sound = "minecraft:music.overworld.dripstone_caves",
                    .min_delay = 12000,
                    .max_delay = 24000,
                    .replace_current_music = false,
                },
            },
        },
    },
    .{
        .name = "minecraft:end_barrens",
        .id = 16,
        .element = .{
            .has_precipitation = false,
            .temperature = 0.5,
            .temperature_modifier = null,
            .downfall = 0.5,
            .effects = .{
                .fog_color = 10518688,
                .water_color = 4159204,
                .water_fog_color = 329011,
                .sky_color = 0,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = null,
            },
        },
    },
    .{
        .name = "minecraft:end_highlands",
        .id = 17,
        .element = .{
            .has_precipitation = false,
            .temperature = 0.5,
            .temperature_modifier = null,
            .downfall = 0.5,
            .effects = .{
                .fog_color = 10518688,
                .water_color = 4159204,
                .water_fog_color = 329011,
                .sky_color = 0,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = null,
            },
        },
    },
    .{
        .name = "minecraft:end_midlands",
        .id = 18,
        .element = .{
            .has_precipitation = false,
            .temperature = 0.5,
            .temperature_modifier = null,
            .downfall = 0.5,
            .effects = .{
                .fog_color = 10518688,
                .water_color = 4159204,
                .water_fog_color = 329011,
                .sky_color = 0,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = null,
            },
        },
    },
    .{
        .name = "minecraft:eroded_badlands",
        .id = 19,
        .element = .{
            .has_precipitation = false,
            .temperature = 2,
            .temperature_modifier = null,
            .downfall = 0,
            .effects = .{
                .fog_color = 12638463,
                .water_color = 4159204,
                .water_fog_color = 329011,
                .sky_color = 7254527,
                .foliage_color = 10387789,
                .grass_color = 9470285,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = .{
                    .sound = "minecraft:music.overworld.badlands",
                    .min_delay = 12000,
                    .max_delay = 24000,
                    .replace_current_music = false,
                },
            },
        },
    },
    .{
        .name = "minecraft:flower_forest",
        .id = 20,
        .element = .{
            .has_precipitation = true,
            .temperature = 0.699999988079071,
            .temperature_modifier = null,
            .downfall = 0.800000011920929,
            .effects = .{
                .fog_color = 12638463,
                .water_color = 4159204,
                .water_fog_color = 329011,
                .sky_color = 7972607,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = .{
                    .sound = "minecraft:music.overworld.flower_forest",
                    .min_delay = 12000,
                    .max_delay = 24000,
                    .replace_current_music = false,
                },
            },
        },
    },
    .{
        .name = "minecraft:forest",
        .id = 21,
        .element = .{
            .has_precipitation = true,
            .temperature = 0.699999988079071,
            .temperature_modifier = null,
            .downfall = 0.800000011920929,
            .effects = .{
                .fog_color = 12638463,
                .water_color = 4159204,
                .water_fog_color = 329011,
                .sky_color = 7972607,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = .{
                    .sound = "minecraft:music.overworld.forest",
                    .min_delay = 12000,
                    .max_delay = 24000,
                    .replace_current_music = false,
                },
            },
        },
    },
    .{
        .name = "minecraft:frozen_ocean",
        .id = 22,
        .element = .{
            .has_precipitation = true,
            .temperature = 0,
            .temperature_modifier = "frozen",
            .downfall = 0.5,
            .effects = .{
                .fog_color = 12638463,
                .water_color = 3750089,
                .water_fog_color = 329011,
                .sky_color = 8364543,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = null,
            },
        },
    },
    .{
        .name = "minecraft:frozen_peaks",
        .id = 23,
        .element = .{
            .has_precipitation = true,
            .temperature = -0.699999988079071,
            .temperature_modifier = null,
            .downfall = 0.8999999761581421,
            .effects = .{
                .fog_color = 12638463,
                .water_color = 4159204,
                .water_fog_color = 329011,
                .sky_color = 8756735,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = .{
                    .sound = "minecraft:music.overworld.frozen_peaks",
                    .min_delay = 12000,
                    .max_delay = 24000,
                    .replace_current_music = false,
                },
            },
        },
    },
    .{
        .name = "minecraft:frozen_river",
        .id = 24,
        .element = .{
            .has_precipitation = true,
            .temperature = 0,
            .temperature_modifier = null,
            .downfall = 0.5,
            .effects = .{
                .fog_color = 12638463,
                .water_color = 3750089,
                .water_fog_color = 329011,
                .sky_color = 8364543,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = null,
            },
        },
    },
    .{
        .name = "minecraft:grove",
        .id = 25,
        .element = .{
            .has_precipitation = true,
            .temperature = -0.20000000298023224,
            .temperature_modifier = null,
            .downfall = 0.800000011920929,
            .effects = .{
                .fog_color = 12638463,
                .water_color = 4159204,
                .water_fog_color = 329011,
                .sky_color = 8495359,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = .{
                    .sound = "minecraft:music.overworld.grove",
                    .min_delay = 12000,
                    .max_delay = 24000,
                    .replace_current_music = false,
                },
            },
        },
    },
    .{
        .name = "minecraft:ice_spikes",
        .id = 26,
        .element = .{
            .has_precipitation = true,
            .temperature = 0,
            .temperature_modifier = null,
            .downfall = 0.5,
            .effects = .{
                .fog_color = 12638463,
                .water_color = 4159204,
                .water_fog_color = 329011,
                .sky_color = 8364543,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = null,
            },
        },
    },
    .{
        .name = "minecraft:jagged_peaks",
        .id = 27,
        .element = .{
            .has_precipitation = true,
            .temperature = -0.699999988079071,
            .temperature_modifier = null,
            .downfall = 0.8999999761581421,
            .effects = .{
                .fog_color = 12638463,
                .water_color = 4159204,
                .water_fog_color = 329011,
                .sky_color = 8756735,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = .{
                    .sound = "minecraft:music.overworld.jagged_peaks",
                    .min_delay = 12000,
                    .max_delay = 24000,
                    .replace_current_music = false,
                },
            },
        },
    },
    .{
        .name = "minecraft:jungle",
        .id = 28,
        .element = .{
            .has_precipitation = true,
            .temperature = 0.949999988079071,
            .temperature_modifier = null,
            .downfall = 0.8999999761581421,
            .effects = .{
                .fog_color = 12638463,
                .water_color = 4159204,
                .water_fog_color = 329011,
                .sky_color = 7842047,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = .{
                    .sound = "minecraft:music.overworld.jungle",
                    .min_delay = 12000,
                    .max_delay = 24000,
                    .replace_current_music = false,
                },
            },
        },
    },
    .{
        .name = "minecraft:lukewarm_ocean",
        .id = 29,
        .element = .{
            .has_precipitation = true,
            .temperature = 0.5,
            .temperature_modifier = null,
            .downfall = 0.5,
            .effects = .{
                .fog_color = 12638463,
                .water_color = 4566514,
                .water_fog_color = 267827,
                .sky_color = 8103167,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = null,
            },
        },
    },
    .{
        .name = "minecraft:lush_caves",
        .id = 30,
        .element = .{
            .has_precipitation = true,
            .temperature = 0.5,
            .temperature_modifier = null,
            .downfall = 0.5,
            .effects = .{
                .fog_color = 12638463,
                .water_color = 4159204,
                .water_fog_color = 329011,
                .sky_color = 8103167,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = .{
                    .sound = "minecraft:music.overworld.lush_caves",
                    .min_delay = 12000,
                    .max_delay = 24000,
                    .replace_current_music = false,
                },
            },
        },
    },
    .{
        .name = "minecraft:mangrove_swamp",
        .id = 31,
        .element = .{
            .has_precipitation = true,
            .temperature = 0.800000011920929,
            .temperature_modifier = null,
            .downfall = 0.8999999761581421,
            .effects = .{
                .fog_color = 12638463,
                .water_color = 3832426,
                .water_fog_color = 5077600,
                .sky_color = 7907327,
                .foliage_color = 9285927,
                .grass_color = null,
                .grass_color_modifier = "swamp",
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = .{
                    .sound = "minecraft:music.overworld.swamp",
                    .min_delay = 12000,
                    .max_delay = 24000,
                    .replace_current_music = false,
                },
            },
        },
    },
    .{
        .name = "minecraft:meadow",
        .id = 32,
        .element = .{
            .has_precipitation = true,
            .temperature = 0.5,
            .temperature_modifier = null,
            .downfall = 0.800000011920929,
            .effects = .{
                .fog_color = 12638463,
                .water_color = 937679,
                .water_fog_color = 329011,
                .sky_color = 8103167,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = .{
                    .sound = "minecraft:music.overworld.meadow",
                    .min_delay = 12000,
                    .max_delay = 24000,
                    .replace_current_music = false,
                },
            },
        },
    },
    .{
        .name = "minecraft:mushroom_fields",
        .id = 33,
        .element = .{
            .has_precipitation = true,
            .temperature = 0.8999999761581421,
            .temperature_modifier = null,
            .downfall = 1,
            .effects = .{
                .fog_color = 12638463,
                .water_color = 4159204,
                .water_fog_color = 329011,
                .sky_color = 7842047,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = null,
            },
        },
    },
    .{
        .name = "minecraft:nether_wastes",
        .id = 34,
        .element = .{
            .has_precipitation = false,
            .temperature = 2,
            .temperature_modifier = null,
            .downfall = 0,
            .effects = .{
                .fog_color = 3344392,
                .water_color = 4159204,
                .water_fog_color = 329011,
                .sky_color = 7254527,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = .{ .string = "minecraft:ambient.nether_wastes.loop" },
                .mood_sound = .{
                    .sound = "minecraft:ambient.nether_wastes.mood",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = .{
                    .sound = "minecraft:ambient.nether_wastes.additions",
                    .tick_chance = 0.0111,
                },
                .music = .{
                    .sound = "minecraft:music.nether.nether_wastes",
                    .min_delay = 12000,
                    .max_delay = 24000,
                    .replace_current_music = false,
                },
            },
        },
    },
    .{
        .name = "minecraft:ocean",
        .id = 35,
        .element = .{
            .has_precipitation = true,
            .temperature = 0.5,
            .temperature_modifier = null,
            .downfall = 0.5,
            .effects = .{
                .fog_color = 12638463,
                .water_color = 4159204,
                .water_fog_color = 329011,
                .sky_color = 8103167,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = null,
            },
        },
    },
    .{
        .name = "minecraft:old_growth_birch_forest",
        .id = 36,
        .element = .{
            .has_precipitation = true,
            .temperature = 0.6000000238418579,
            .temperature_modifier = null,
            .downfall = 0.6000000238418579,
            .effects = .{
                .fog_color = 12638463,
                .water_color = 4159204,
                .water_fog_color = 329011,
                .sky_color = 8037887,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = .{
                    .sound = "minecraft:music.overworld.forest",
                    .min_delay = 12000,
                    .max_delay = 24000,
                    .replace_current_music = false,
                },
            },
        },
    },
    .{
        .name = "minecraft:old_growth_pine_taiga",
        .id = 37,
        .element = .{
            .has_precipitation = true,
            .temperature = 0.30000001192092896,
            .temperature_modifier = null,
            .downfall = 0.800000011920929,
            .effects = .{
                .fog_color = 12638463,
                .water_color = 4159204,
                .water_fog_color = 329011,
                .sky_color = 8168447,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = .{
                    .sound = "minecraft:music.overworld.old_growth_taiga",
                    .min_delay = 12000,
                    .max_delay = 24000,
                    .replace_current_music = false,
                },
            },
        },
    },
    .{
        .name = "minecraft:old_growth_spruce_taiga",
        .id = 38,
        .element = .{
            .has_precipitation = true,
            .temperature = 0.25,
            .temperature_modifier = null,
            .downfall = 0.800000011920929,
            .effects = .{
                .fog_color = 12638463,
                .water_color = 4159204,
                .water_fog_color = 329011,
                .sky_color = 8233983,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = .{
                    .sound = "minecraft:music.overworld.old_growth_taiga",
                    .min_delay = 12000,
                    .max_delay = 24000,
                    .replace_current_music = false,
                },
            },
        },
    },
    .{
        .name = "minecraft:plains",
        .id = 39,
        .element = .{
            .has_precipitation = true,
            .temperature = 0.800000011920929,
            .temperature_modifier = null,
            .downfall = 0.4000000059604645,
            .effects = .{
                .fog_color = 12638463,
                .water_color = 4159204,
                .water_fog_color = 329011,
                .sky_color = 7907327,
                .foliage_color = null,
                .grass_color = null,
                .grass_color_modifier = null,
                .particle = null,
                .ambient_sound = null,
                .mood_sound = .{
                    .sound = "minecraft:ambient.cave",
                    .tick_delay = 6000,
                    .block_search_extent = 8,
                    .offset = 2,
                },
                .additions_sound = null,
                .music = null,
            },
        },
    },

    //.{
    //    .name = "minecraft:plains",
    //    .id = 0,
    //    .element = .{
    //        .has_precipitation = true,
    //        .temperature = 0.8,
    //        .downfall = 0.4,
    //        .effects = .{
    //            .sky_color = 0x78A7FF,
    //            .water_fog_color = 0x050533,
    //            .fog_color = 0xC0D8FF,
    //            .water_color = 0x3F76E4,
    //            .mood_sound = .{
    //                .tick_delay = 6000,
    //                .offset = 2.0,
    //                .sound = "minecraft:ambient.cave",
    //                .block_search_extent = 8,
    //            },
    //        },
    //    },
    //},
};
pub const default_chats = .{.{
    .name = "minecraft:chat",
    .id = 0,
    .element = .{
        .chat = .{
            .translation_key = "chat.type.text",
            .parameters = &.{ .sender, .content },
        },
        .narration = .{
            .translation_key = "chat.type.text.narrate",
            .parameters = &.{ .sender, .content },
        },
    },
}};

pub const DefaultRegistry = mcv.RegistryData.UT{
    .trim_material = .{ .value = &.{} },
    .trim_pattern = .{ .value = &.{} },
    .damage_type = .{ .value = &default_damage_types },
    .biome = .{ .value = &default_biomes },
    .chat_type = .{ .value = &default_chats },
    .dimension_type = .{ .value = &.{.{
        .name = "minecraft:overworld",
        .id = 0,
        .element = .{
            .piglin_safe = false,
            .natural = true,
            .ambient_light = 0.0,
            .monster_spawn_block_light_limit = 0,
            .infiniburn = "#minecraft:infiniburn_overworld",
            .respawn_anchor_works = false,
            .has_skylight = true,
            .bed_works = true,
            .effects = .overworld,
            .has_raids = true,
            .logical_height = mcp.chunk.HEIGHT,
            .coordinate_scale = 1.0,
            .monster_spawn_light_level = .{ .compound = .{
                .type = .uniform,
                .value = .{ .min_inclusive = 0, .max_inclusive = 7 },
            } },
            .min_y = mcp.chunk.MIN_Y,
            .ultrawarm = false,
            .has_ceiling = false,
            .height = mcp.chunk.HEIGHT,
        },
    }} },
};

test "default registry" {
    @setEvalBranchQuota(10_000);
    try mcp.nbt.doDynamicTestOnValue(mcv.RegistryData, DefaultRegistry, true, false);
}
